version: "3.9"

services:
  api:
    build: .
    container_name: launchpad-api
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: launchpad@123
      DB_NAME: launchpad_db
      JWT_SECRET: supersecret
    depends_on:
      - db
    volumes:
      - .:/app              # Mount local code for live reload
      - /app/node_modules   # Keep node_modules inside container only
    command: npm run dev     # Use dev command with ts-node-dev

  db:
    image: postgres:16
    container_name: launchpad-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: launchpad@123
      POSTGRES_DB: launchpad_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: