name: Deploy to Utho VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/CMS-BACKEND
            git pull origin dev
            npm ci
            npm run build:auth
            npm run build:contest-management
            npm run build:form-builder
            npm run build:user
            pm2 restart auth
            pm2 restart contest-management-service
            pm2 restart formbuilder-service
            pm2 restart user-service
